[phases.install]
cmds = [
  "composer install --ignore-platform-reqs --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan route:clear",
  "php artisan view:clear"
]

[start]
cmd = "bash start.sh"

