[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.mbstring",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.curl",
  "php82Extensions.fileinfo",
  "php82Extensions.openssl"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --ignore-platform-reqs"
]

[phases.build]
cmds = [
  "echo 'Build done, artisan commands will run in release phase.'"
]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/"
