[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = [
  "php82",
  "php82Packages.composer",
  "php82Extensions.mbstring",
  "php82Extensions.pdo",
  "php82Extensions.pdo_mysql",
  "php82Extensions.tokenizer",
  "php82Extensions.xml",
  "php82Extensions.curl",
  "php82Extensions.fileinfo",
  "php82Extensions.openssl"
]

[phases.install]
cmds = [
  "composer install --ignore-platform-reqs --no-dev --optimize-autoloader"
]

[phases.build]
cmds = [
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan route:clear",
  "php artisan view:clear",
  "php artisan migrate --force"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=8000"
